"""
api/main.py

FastAPI REST API for the PDF heading extractor.

Run locally:
    uvicorn api.main:app --reload --port 8000

Endpoints:
    POST /extract   — extract headings from a single PDF
    GET  /health    — health check
    GET  /docs      — Swagger UI (auto-generated by FastAPI)
"""

from __future__ import annotations

import logging
import os
import tempfile
import time
from pathlib import Path

from fastapi import FastAPI, File, HTTPException, Query, UploadFile, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles

from api.schemas import (
    BoundingBoxResponse,
    ErrorResponse,
    ExtractResponse,
    ExtractionMetadataResponse,
    HealthResponse,
    HeadingResponse,
)
from extractor.core import ExtractorEngine
from extractor.models import DocumentOutline
from extractor.utils import describe_confidence, is_valid_pdf

# ── Logging ────────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
log = logging.getLogger("api")

# ── Constants ──────────────────────────────────────────────────────────────────

MAX_FILE_SIZE_MB = 20
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
API_VERSION = "0.1.0"

# ── App initialisation ─────────────────────────────────────────────────────────

app = FastAPI(
    title="PDF Heading Extractor API",
    description=(
        "A production-grade PDF document-structure extraction engine.\n\n"
        "Upload a PDF and receive a structured JSON outline of its headings (H1/H2/H3) "
        "with confidence scores, font metadata, and bounding boxes."
    ),
    version=API_VERSION,
    contact={
        "name": "GitHub Repository",
        "url": "https://github.com/harsh07032004/PDF_HEADINGEXTRACTOR",
    },
    license_info={"name": "ME"},
)

# CORS — allow all origins for local dev; restrict via ALLOWED_ORIGINS env var in prod
allowed_origins_env = os.environ.get("ALLOWED_ORIGINS", "*")
allowed_origins = (
    [o.strip() for o in allowed_origins_env.split(",")]
    if allowed_origins_env != "*"
    else ["*"]
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=False,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ── Helper: convert engine output → API response ───────────────────────────────

def _outline_to_response(outline: DocumentOutline, min_confidence: float) -> ExtractResponse:
    """Convert a DocumentOutline dataclass into an ExtractResponse Pydantic model."""
    heading_responses = [
        HeadingResponse(
            level=h.level,
            text=h.text,
            page=h.page,
            confidence=h.confidence,
            font_name=h.font_name,
            font_size=h.font_size,
            bounding_box=BoundingBoxResponse(
                x0=h.bounding_box.x0,
                y0=h.bounding_box.y0,
                x1=h.bounding_box.x1,
                y1=h.bounding_box.y1,
            ),
            confidence_label=describe_confidence(h.confidence),
        )
        for h in outline.headings
        if h.confidence >= min_confidence
    ]

    meta = ExtractionMetadataResponse(
        filename=outline.filename,
        total_pages=outline.total_pages,
        language=outline.metadata.language,
        toc_available=outline.metadata.toc_available,
        scanned_pdf_detected=outline.metadata.scanned_pdf_detected,
        processing_time_ms=outline.metadata.processing_time_ms,
        engine_version=outline.metadata.engine_version,
    )

    return ExtractResponse(title=outline.title, outline=heading_responses, metadata=meta)


async def _save_upload_to_temp(upload: UploadFile) -> Path:
    """
    Save an UploadFile to a temporary file and return its Path.
    Enforces MAX_FILE_SIZE_BYTES; raises HTTPException(413) if exceeded.
    """
    suffix = Path(upload.filename or "upload.pdf").suffix or ".pdf"
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
    tmp_path = Path(tmp.name)
    total = 0

    try:
        while chunk := await upload.read(65536):
            total += len(chunk)
            if total > MAX_FILE_SIZE_BYTES:
                tmp.close()
                tmp_path.unlink(missing_ok=True)
                raise HTTPException(
                    status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                    detail=f"File exceeds the {MAX_FILE_SIZE_MB} MB limit.",
                )
            tmp.write(chunk)
    finally:
        tmp.close()

    return tmp_path


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.get("/health", response_model=HealthResponse, summary="Health check", tags=["System"])
async def health() -> HealthResponse:
    """Liveness probe — returns status + engine version."""
    return HealthResponse(version=API_VERSION)


@app.post(
    "/extract",
    response_model=ExtractResponse,
    summary="Extract headings from a single PDF",
    tags=["Extraction"],
    responses={
        400: {"model": ErrorResponse, "description": "Invalid file or parameters"},
        413: {"model": ErrorResponse, "description": "File too large"},
        500: {"model": ErrorResponse, "description": "Extraction error"},
    },
)
async def extract(
    file: UploadFile = File(..., description="PDF file to process."),
    min_confidence: float = Query(
        default=0.45, ge=0.0, le=1.0,
        description="Minimum confidence threshold (0.0–1.0).",
    ),
    use_ml: bool = Query(
        default=True, description="Use the trained ML model for heading classification."
    ),
) -> ExtractResponse:
    """
    Upload a PDF and receive its heading structure.

    Response contains:
    - **title**: detected document title
    - **outline**: list of headings with level (H1/H2/H3), page, confidence,
      font metadata, and bounding box coordinates
    - **metadata**: processing stats (timing, TOC availability, scanned detection)
    """
    tmp_path = await _save_upload_to_temp(file)

    try:
        if not is_valid_pdf(tmp_path):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Uploaded file does not appear to be a valid PDF.",
            )

        log.info("Extracting: %s", file.filename)

        with ExtractorEngine(tmp_path, use_ml=use_ml) as engine:
            outline = engine.process()

        if outline.metadata.scanned_pdf_detected:
            log.warning("Scanned PDF detected: %s", file.filename)

        return _outline_to_response(outline, min_confidence)

    except HTTPException:
        raise
    except Exception as exc:
        log.exception("Extraction failed for %s", file.filename)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Extraction failed: {exc}",
        ) from exc
    finally:
        tmp_path.unlink(missing_ok=True)


# ── Static Frontend ────────────────────────────────────────────────────────────

app.mount("/", StaticFiles(directory="frontend", html=True), name="frontend")


# ── Global exception handlers ──────────────────────────────────────────────────

@app.exception_handler(404)
async def not_found_handler(_req: object, _exc: object) -> JSONResponse:
    return JSONResponse(status_code=404, content={"error": "Not found", "status_code": 404})


@app.exception_handler(500)
async def server_error_handler(_req: object, exc: Exception) -> JSONResponse:
    log.exception("Unhandled server error")
    return JSONResponse(
        status_code=500,
        content={"error": "Internal server error", "detail": str(exc), "status_code": 500},
    )
