"""
api/main.py

FastAPI application — production-grade REST API for the PDF heading extractor.

Run locally:
    uvicorn api.main:app --reload --port 8000

Endpoints:
    POST /extract              — extract headings from a single PDF
    POST /extract/batch        — extract headings from multiple PDFs
    GET  /health               — health check (used by Docker/K8s probes)
    GET  /languages            — list supported language codes
    GET  /docs                 — Swagger UI (auto-generated by FastAPI)
    GET  /redoc                — ReDoc UI (auto-generated by FastAPI)
"""

from __future__ import annotations

import json
import logging
import tempfile
import time
from pathlib import Path

from fastapi import (
    FastAPI,
    File,
    HTTPException,
    Query,
    UploadFile,
    status,
)
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles

from api.schemas import (
    BatchExtractResponse,
    BoundingBoxResponse,
    ErrorResponse,
    ExtractResponse,
    ExtractionMetadataResponse,
    HealthResponse,
    HeadingResponse,
    LanguagesResponse,
)
from extractor.core import ExtractorEngine
from extractor.models import DocumentOutline
from extractor.utils import describe_confidence, is_valid_pdf

# ── Logging ────────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
)
log = logging.getLogger("api")

# ── Constants ──────────────────────────────────────────────────────────────────

MAX_FILE_SIZE_MB = 20
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
SUPPORTED_LANGUAGES = ["en", "es", "fr", "de", "ja"]
API_VERSION = "0.1.0"

# ── App initialisation ─────────────────────────────────────────────────────────

app = FastAPI(
    title="PDF Heading Extractor API",
    description=(
        "A production-grade multilingual PDF document-structure extraction engine.\n\n"
        "Upload a PDF and receive a structured JSON outline of its headings (H1/H2/H3) "
        "with confidence scores, font metadata, and bounding boxes."
    ),
    version=API_VERSION,
    contact={
        "name": "GitHub Repository",
        "url": "https://github.com/Harshitaaaaaaaaaa/Adobe-hackathon-1A",
    },
    license_info={"name": "MIT"},
)

# CORS — allow all origins for local development; restrict in production
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# Serve the Web UI from /web if the directory exists
_web_dir = Path(__file__).parent.parent / "web"
if _web_dir.is_dir():
    app.mount("/ui", StaticFiles(directory=str(_web_dir), html=True), name="web")


# ── Helper: convert engine output → API response ───────────────────────────────

def _outline_to_response(outline: DocumentOutline, min_confidence: float) -> ExtractResponse:
    """Convert a DocumentOutline dataclass into an ExtractResponse Pydantic model."""
    heading_responses = [
        HeadingResponse(
            level=h.level,
            text=h.text,
            page=h.page,
            confidence=h.confidence,
            font_name=h.font_name,
            font_size=h.font_size,
            bounding_box=BoundingBoxResponse(
                x0=h.bounding_box.x0,
                y0=h.bounding_box.y0,
                x1=h.bounding_box.x1,
                y1=h.bounding_box.y1,
            ),
            confidence_label=describe_confidence(h.confidence),
        )
        for h in outline.headings
        if h.confidence >= min_confidence
    ]

    meta = ExtractionMetadataResponse(
        filename=outline.filename,
        total_pages=outline.total_pages,
        language=outline.metadata.language,
        toc_available=outline.metadata.toc_available,
        scanned_pdf_detected=outline.metadata.scanned_pdf_detected,
        processing_time_ms=outline.metadata.processing_time_ms,
        engine_version=outline.metadata.engine_version,
    )

    return ExtractResponse(
        title=outline.title,
        outline=heading_responses,
        metadata=meta,
    )


async def _save_upload_to_temp(upload: UploadFile) -> Path:
    """
    Save an UploadFile to a temporary file and return its Path.

    Enforces the MAX_FILE_SIZE_BYTES limit by counting bytes as we stream.
    Raises HTTPException(413) if exceeded.
    """
    suffix = Path(upload.filename or "upload.pdf").suffix or ".pdf"
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
    tmp_path = Path(tmp.name)
    total = 0

    try:
        while chunk := await upload.read(65536):
            total += len(chunk)
            if total > MAX_FILE_SIZE_BYTES:
                tmp.close()
                tmp_path.unlink(missing_ok=True)
                raise HTTPException(
                    status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                    detail=f"File exceeds the {MAX_FILE_SIZE_MB} MB limit.",
                )
            tmp.write(chunk)
    finally:
        tmp.close()

    return tmp_path


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Health check",
    tags=["System"],
)
async def health() -> HealthResponse:
    """
    Liveness probe endpoint.

    Returns ``{"status": "ok"}`` with the current engine version.
    Used by Docker HEALTHCHECK and Kubernetes liveness probes.
    """
    return HealthResponse(version=API_VERSION)


@app.get(
    "/languages",
    response_model=LanguagesResponse,
    summary="List supported languages",
    tags=["System"],
)
async def get_languages() -> LanguagesResponse:
    """
    Returns the list of language codes available for heading pattern matching.
    Pass the chosen code as the ``lang`` query parameter on ``/extract``.
    """
    return LanguagesResponse(supported=SUPPORTED_LANGUAGES)


@app.post(
    "/extract",
    response_model=ExtractResponse,
    summary="Extract headings from a single PDF",
    tags=["Extraction"],
    responses={
        400: {"model": ErrorResponse, "description": "Invalid file or parameters"},
        413: {"model": ErrorResponse, "description": "File too large"},
        422: {"model": ErrorResponse, "description": "Validation error"},
        500: {"model": ErrorResponse, "description": "Extraction error"},
    },
)
async def extract(
    file: UploadFile = File(..., description="PDF file to process."),
    lang: str = Query(default="en", description="Language code (en, es, fr, de, ja)."),
    min_confidence: float = Query(
        default=0.45, ge=0.0, le=1.0,
        description="Minimum confidence threshold (0.0–1.0).",
    ),
    use_ml: bool = Query(
        default=True, description="Use the trained ML model for heading classification."
    ),
) -> ExtractResponse:
    """
    Upload a PDF file and receive its heading structure.

    The response contains:
    - **title**: detected document title
    - **outline**: list of headings with level (H1/H2/H3), page, confidence,
      font metadata, and bounding box coordinates
    - **metadata**: processing stats (timing, TOC availability, scanned detection)
    """
    if lang not in SUPPORTED_LANGUAGES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unsupported language '{lang}'. Choose from: {SUPPORTED_LANGUAGES}",
        )

    tmp_path = await _save_upload_to_temp(file)

    try:
        if not is_valid_pdf(tmp_path):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Uploaded file does not appear to be a valid PDF.",
            )

        log.info("Extracting: %s  lang=%s", file.filename, lang)

        with ExtractorEngine(tmp_path, lang=lang, use_ml=use_ml) as engine:
            outline = engine.process()

        if outline.metadata.scanned_pdf_detected:
            log.warning("Scanned PDF detected: %s", file.filename)

        return _outline_to_response(outline, min_confidence)

    except HTTPException:
        raise
    except Exception as exc:
        log.exception("Extraction failed for %s", file.filename)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Extraction failed: {exc}",
        ) from exc
    finally:
        tmp_path.unlink(missing_ok=True)


@app.post(
    "/extract/batch",
    response_model=BatchExtractResponse,
    summary="Extract headings from multiple PDFs",
    tags=["Extraction"],
)
async def extract_batch(
    files: list[UploadFile] = File(..., description="PDF files to process (max 10)."),
    lang: str = Query(default="en", description="Language code applied to all files."),
    min_confidence: float = Query(default=0.45, ge=0.0, le=1.0),
    use_ml: bool = Query(default=True),
) -> BatchExtractResponse:
    """
    Upload up to 10 PDF files and receive heading structures for all of them.

    Files are processed sequentially. Failed files are reported in the
    ``failed`` count without aborting the rest of the batch.
    """
    if len(files) > 10:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Batch endpoint accepts a maximum of 10 files per request.",
        )

    if lang not in SUPPORTED_LANGUAGES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unsupported language '{lang}'.",
        )

    batch_start = time.perf_counter()
    results: list[ExtractResponse] = []
    failed = 0

    for upload in files:
        tmp_path = await _save_upload_to_temp(upload)
        try:
            if not is_valid_pdf(tmp_path):
                log.warning("Skipping non-PDF: %s", upload.filename)
                failed += 1
                continue

            with ExtractorEngine(tmp_path, lang=lang, use_ml=use_ml) as engine:
                outline = engine.process()

            results.append(_outline_to_response(outline, min_confidence))
            log.info("Batch item OK: %s", upload.filename)

        except Exception as exc:
            log.error("Batch item failed (%s): %s", upload.filename, exc)
            failed += 1
        finally:
            tmp_path.unlink(missing_ok=True)

    total_ms = round((time.perf_counter() - batch_start) * 1000, 2)

    return BatchExtractResponse(
        results=results,
        total_files=len(files),
        successful=len(results),
        failed=failed,
        total_processing_time_ms=total_ms,
    )


# ── Global exception handlers ──────────────────────────────────────────────────

@app.exception_handler(404)
async def not_found_handler(_req: object, _exc: object) -> JSONResponse:
    return JSONResponse(
        status_code=404,
        content={"error": "Not found", "status_code": 404},
    )


@app.exception_handler(500)
async def server_error_handler(_req: object, exc: Exception) -> JSONResponse:
    log.exception("Unhandled server error")
    return JSONResponse(
        status_code=500,
        content={"error": "Internal server error", "detail": str(exc), "status_code": 500},
    )
